services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb

  test_register:
    build:
      context: .
    environment:
      REMOTE_WEBDRIVER_URL: http://selenium:4444/wd/hub
      SKIP_LANGUAGE_SELECTION: "1"
    command: pytest -q test_acy_register.py
    depends_on:
      - selenium
