version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always

  test_register:
    build:
      context: .
    volumes:
      - ./test_docker:/test_docker
    command: sh -c "pytest test_acy_register.py"
    depends_on:
      - selenium
